

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
